/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef KOP32_DEV_PRIVATE_H
#define KOP32_DEV_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.8.0.2501"
#define VER_MAJOR	0
#define VER_MINOR	8
#define VER_RELEASE	0
#define VER_BUILD	2501
#define COMPANY_NAME	""
#define FILE_VERSION	"0.8.0.2501"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	"Koperek"
#define LEGAL_COPYRIGHT	"SSTSOFT.pl"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"0.8.0.2501"

#endif /*KOP32_DEV_PRIVATE_H*/
