#############################################################################
# Makefile for building: libstk.so.1.0.0
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  stk.pro
# Template: lib
# Command: /usr/bin/qmake-qt5 -spec linux-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile stk.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DBUILD_STK_LIBRARY -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/lib64/qt5/mkspecs/linux-clang
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = stk1.0.0
DISTDIR = /mnt/D/DOK/My\ Projects/X86_LIBRARIES/STK/.tmp/stk1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -shared -Wl,-soname,libstk.so.1
LIBS          = $(SUBLIBS)  
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = stk_set.cpp \
		stk_test.cpp \
		stk_hash_chain.cpp \
		stk_list.cpp \
		stk_map.cpp \
		cpu/stk_cpu.cpp \
		cipher/stk_base64.cpp \
		cipher/stk_cipher_mtf.cpp \
		cipher/stk_cipher_API.cpp \
		cipher/stk_cipher_pair.cpp \
		compression/stk_compression_ari.cpp \
		compression/stk_compression_bwt_matrix2.cpp \
		compression/stk_compression_huff.cpp \
		compression/stk_compression_lzstv4.cpp \
		compression/stk_compression_static_huff.cpp \
		compression/stk_compression_API.cpp \
		database/stk_database_items.cpp \
		database/stk_database.cpp \
		file/stk_file_mime_types.cpp \
		file/ini/stk_file_ini.cpp \
		file/eno/stk_file_lzst_header.cpp \
		file/json/stk_json.cpp \
		file/vfs/stk_file_vfs.cpp \
		file/xml/stk_xml.cpp \
		hash/stk_hash_crc32.cpp \
		hash/stk_hash_md5.cpp \
		hash/stk_hash_password.cpp \
		hash/stk_hash_ssc1.cpp \
		hash/md5/md5.c \
		hash/sha1/hmac_sha1.c \
		hash/sha1/sha1.c \
		io/stk_file_io.cpp \
		io/stk_rs232.cpp \
		io/stk_console.cpp \
		koperek/stk_kop32_class.cpp \
		koperek/stk_kop32_controler.cpp \
		koperek/stk_kop32_search.cpp \
		koperek/stk_kop32_socket_server.cpp \
		koperek/stk_kop32_API.cpp \
		mem/stk_mem.cpp \
		mem/stk_btree.cpp \
		process_journal/stk_journal.cpp \
		pharser/stk_pharse_command_line.cpp \
		pharser/stk_pharse_math.cpp \
		sockets/stk_sockets.cpp \
		stasm/stk_stasm.cpp \
		threads/stk_threads.cpp \
		text/stk_cstr_utils.cpp \
		time/stk_time.cpp \
		text/stk_cstr_class.cpp \
		text/stk_cstr_stack.cpp \
		koperek/stk_kop32_options.cpp \
		koperek/stk_kop32_list.cpp \
		file/zip/miniz.c 
OBJECTS       = stk_set.o \
		stk_test.o \
		stk_hash_chain.o \
		stk_list.o \
		stk_map.o \
		stk_cpu.o \
		stk_base64.o \
		stk_cipher_mtf.o \
		stk_cipher_API.o \
		stk_cipher_pair.o \
		stk_compression_ari.o \
		stk_compression_bwt_matrix2.o \
		stk_compression_huff.o \
		stk_compression_lzstv4.o \
		stk_compression_static_huff.o \
		stk_compression_API.o \
		stk_database_items.o \
		stk_database.o \
		stk_file_mime_types.o \
		stk_file_ini.o \
		stk_file_lzst_header.o \
		stk_json.o \
		stk_file_vfs.o \
		stk_xml.o \
		stk_hash_crc32.o \
		stk_hash_md5.o \
		stk_hash_password.o \
		stk_hash_ssc1.o \
		md5.o \
		hmac_sha1.o \
		sha1.o \
		stk_file_io.o \
		stk_rs232.o \
		stk_console.o \
		stk_kop32_class.o \
		stk_kop32_controler.o \
		stk_kop32_search.o \
		stk_kop32_socket_server.o \
		stk_kop32_API.o \
		stk_mem.o \
		stk_btree.o \
		stk_journal.o \
		stk_pharse_command_line.o \
		stk_pharse_math.o \
		stk_sockets.o \
		stk_stasm.o \
		stk_threads.o \
		stk_cstr_utils.o \
		stk_time.o \
		stk_cstr_class.o \
		stk_cstr_stack.o \
		stk_kop32_options.o \
		stk_kop32_list.o \
		miniz.o
DIST          = test.txt \
		/usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/clang.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		stk.pro stk_hash_chain.h \
		stk_list.h \
		stk_main.h \
		stk_map.h \
		stk_set.h \
		stk_vector.h \
		3D/stk_3Dvector.h \
		cpu/stk_cpu.h \
		cipher/stk_cipher_API.h \
		cipher/stk_cipher_mtf.h \
		cipher/stk_cipher_pair.h \
		cipher/stk_base64.h \
		cipher/FastAESinC/stk_aes.h \
		compression/stk_compression_static_huff.h \
		compression/stk_compression_ari.h \
		compression/stk_compression_bwt_matrix2.h \
		compression/stk_compression_bwt_matrix3_suffix.h \
		compression/stk_compression_huff.h \
		compression/stk_compression_lzstv4.h \
		compression/stk_compression_API.h \
		database/stk_database.h \
		database/stk_database_owner.h \
		database/stk_database_alias.h \
		database/stk_database_items.h \
		file/stk_file_mime_types.h \
		file/ini/stk_file_ini.h \
		file/eno/stk_file_lzst_header.h \
		file/json/stk_json.h \
		file/vfs/stk_file_vfs.h \
		file/xml/stk_xml.h \
		hash/stk_hash_ssc1.h \
		hash/stk_hash_crc32.h \
		hash/stk_hash_md5.h \
		hash/stk_hash_password.h \
		hash/md5/md5.h \
		hash/sha1/hmac_sha1.h \
		hash/sha1/sha.h \
		incbin/stk_incbin.h \
		io/stk_file_io.h \
		io/stk_rs232.h \
		io/stk_console.h \
		koperek/stk_kop32_class.h \
		koperek/stk_kop32_search.h \
		koperek/stk_kop32_controler.h \
		koperek/stk_kop32_list.h \
		koperek/stk_kop32_options.h \
		koperek/stk_kop32_socket_server.h \
		koperek/stk_kop32_API.h \
		mem/stk_mem.h \
		mem/stk_btree.h \
		pharser/stk_pharse_math.h \
		pharser/stk_pharse_command_line.h \
		process_journal/stk_journal.h \
		sockets/stk_sockets.h \
		stasm/stk_stasm.h \
		threads/stk_threads.h \
		time/stk_time.h \
		text/stk_cstr_class.h \
		text/stk_cstr_stack.h \
		text/stk_cstr_utils.h \
		text/stk_cstr.h \
		stk_test.h \
		file/zip/miniz.h stk_set.cpp \
		stk_test.cpp \
		stk_hash_chain.cpp \
		stk_list.cpp \
		stk_map.cpp \
		cpu/stk_cpu.cpp \
		cipher/stk_base64.cpp \
		cipher/stk_cipher_mtf.cpp \
		cipher/stk_cipher_API.cpp \
		cipher/stk_cipher_pair.cpp \
		compression/stk_compression_ari.cpp \
		compression/stk_compression_bwt_matrix2.cpp \
		compression/stk_compression_huff.cpp \
		compression/stk_compression_lzstv4.cpp \
		compression/stk_compression_static_huff.cpp \
		compression/stk_compression_API.cpp \
		database/stk_database_items.cpp \
		database/stk_database.cpp \
		file/stk_file_mime_types.cpp \
		file/ini/stk_file_ini.cpp \
		file/eno/stk_file_lzst_header.cpp \
		file/json/stk_json.cpp \
		file/vfs/stk_file_vfs.cpp \
		file/xml/stk_xml.cpp \
		hash/stk_hash_crc32.cpp \
		hash/stk_hash_md5.cpp \
		hash/stk_hash_password.cpp \
		hash/stk_hash_ssc1.cpp \
		hash/md5/md5.c \
		hash/sha1/hmac_sha1.c \
		hash/sha1/sha1.c \
		io/stk_file_io.cpp \
		io/stk_rs232.cpp \
		io/stk_console.cpp \
		koperek/stk_kop32_class.cpp \
		koperek/stk_kop32_controler.cpp \
		koperek/stk_kop32_search.cpp \
		koperek/stk_kop32_socket_server.cpp \
		koperek/stk_kop32_API.cpp \
		mem/stk_mem.cpp \
		mem/stk_btree.cpp \
		process_journal/stk_journal.cpp \
		pharser/stk_pharse_command_line.cpp \
		pharser/stk_pharse_math.cpp \
		sockets/stk_sockets.cpp \
		stasm/stk_stasm.cpp \
		threads/stk_threads.cpp \
		text/stk_cstr_utils.cpp \
		time/stk_time.cpp \
		text/stk_cstr_class.cpp \
		text/stk_cstr_stack.cpp \
		koperek/stk_kop32_options.cpp \
		koperek/stk_kop32_list.cpp \
		file/zip/miniz.c
QMAKE_TARGET  = stk
DESTDIR       = 
TARGET        = libstk.so.1.0.0
TARGETA       = libstk.a
TARGET0       = libstk.so
TARGETD       = libstk.so.1.0.0
TARGET1       = libstk.so.1
TARGET2       = libstk.so.1.0


first: all
####### Build rules

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: stk.pro /usr/lib64/qt5/mkspecs/linux-clang/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/clang.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-clang/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		stk.pro
	$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile stk.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/clang.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-clang/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/precompile_header.prf:
/usr/lib64/qt5/mkspecs/features/qml_debug.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
stk.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-clang CONFIG+=debug CONFIG+=qml_debug -o Makefile stk.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_no_pch_compiler_make_all:
compiler_no_pch_compiler_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

stk_set.o: stk_set.cpp stk_set.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_set.o stk_set.cpp

stk_test.o: stk_test.cpp stk_test.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		cpu/stk_cpu.h \
		threads/stk_threads.h \
		koperek/stk_kop32_API.h \
		koperek/stk_kop32_class.h \
		text/stk_cstr_stack.h \
		text/stk_cstr_class.h \
		stk_vector.h \
		io/stk_console.h \
		database/stk_database.h \
		database/stk_database_alias.h \
		database/stk_database_items.h \
		koperek/stk_kop32_options.h \
		hash/stk_hash_password.h \
		file/eno/stk_file_lzst_header.h \
		koperek/stk_kop32_list.h \
		koperek/stk_kop32_controler.h \
		koperek/stk_kop32_search.h \
		io/stk_file_io.h \
		compression/stk_compression_API.h \
		cipher/stk_cipher_API.h \
		hash/stk_hash_API.h \
		hash/stk_hash_md5.h \
		hash/stk_hash_ssc1.h \
		stk_tree.h \
		process_journal/stk_journal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_test.o stk_test.cpp

stk_hash_chain.o: stk_hash_chain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_hash_chain.o stk_hash_chain.cpp

stk_list.o: stk_list.cpp stk_list.h \
		mem/stk_mem.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_list.o stk_list.cpp

stk_map.o: stk_map.cpp stk_map.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_map.o stk_map.cpp

stk_cpu.o: cpu/stk_cpu.cpp mem/stk_mem.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		threads/stk_threads.h \
		cpu/stk_cpu.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_cpu.o cpu/stk_cpu.cpp

stk_base64.o: cipher/stk_base64.cpp cipher/stk_base64.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_base64.o cipher/stk_base64.cpp

stk_cipher_mtf.o: cipher/stk_cipher_mtf.cpp cipher/stk_cipher_mtf.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_cipher_mtf.o cipher/stk_cipher_mtf.cpp

stk_cipher_API.o: cipher/stk_cipher_API.cpp cipher/stk_cipher_API.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		file/eno/stk_file_lzst_header.h \
		cipher/stk_cipher_mtf.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_cipher_API.o cipher/stk_cipher_API.cpp

stk_cipher_pair.o: cipher/stk_cipher_pair.cpp cipher/stk_cipher_pair.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_cipher_pair.o cipher/stk_cipher_pair.cpp

stk_compression_ari.o: compression/stk_compression_ari.cpp compression/stk_compression_ari.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_compression_ari.o compression/stk_compression_ari.cpp

stk_compression_bwt_matrix2.o: compression/stk_compression_bwt_matrix2.cpp compression/stk_compression_bwt_matrix2.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_compression_bwt_matrix2.o compression/stk_compression_bwt_matrix2.cpp

stk_compression_huff.o: compression/stk_compression_huff.cpp compression/stk_compression_huff.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_compression_huff.o compression/stk_compression_huff.cpp

stk_compression_lzstv4.o: compression/stk_compression_lzstv4.cpp compression/stk_compression_lzstv4.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		file/eno/stk_file_lzst_header.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_compression_lzstv4.o compression/stk_compression_lzstv4.cpp

stk_compression_static_huff.o: compression/stk_compression_static_huff.cpp compression/stk_compression_static_huff.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_compression_static_huff.o compression/stk_compression_static_huff.cpp

stk_compression_API.o: compression/stk_compression_API.cpp compression/stk_compression_API.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		file/eno/stk_file_lzst_header.h \
		compression/stk_compression_lzstv4.h \
		compression/stk_compression_bwt_matrix2.h \
		compression/stk_compression_huff.h \
		compression/stk_compression_ari.h \
		cipher/stk_cipher_mtf.h \
		io/stk_console.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_compression_API.o compression/stk_compression_API.cpp

stk_database_items.o: database/stk_database_items.cpp io/stk_console.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		database/stk_database.h \
		database/stk_database_alias.h \
		text/stk_cstr_class.h \
		stk_vector.h \
		database/stk_database_items.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_database_items.o database/stk_database_items.cpp

stk_database.o: database/stk_database.cpp io/stk_console.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		database/stk_database.h \
		database/stk_database_alias.h \
		text/stk_cstr_class.h \
		stk_vector.h \
		database/stk_database_items.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_database.o database/stk_database.cpp

stk_file_mime_types.o: file/stk_file_mime_types.cpp mem/stk_mem.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		file/stk_file_mime_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_file_mime_types.o file/stk_file_mime_types.cpp

stk_file_ini.o: file/ini/stk_file_ini.cpp file/ini/stk_file_ini.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_file_ini.o file/ini/stk_file_ini.cpp

stk_file_lzst_header.o: file/eno/stk_file_lzst_header.cpp file/eno/stk_file_lzst_header.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_file_lzst_header.o file/eno/stk_file_lzst_header.cpp

stk_json.o: file/json/stk_json.cpp file/json/stk_json.h \
		mem/stk_mem.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_json.o file/json/stk_json.cpp

stk_file_vfs.o: file/vfs/stk_file_vfs.cpp file/vfs/stk_file_vfs.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_file_vfs.o file/vfs/stk_file_vfs.cpp

stk_xml.o: file/xml/stk_xml.cpp file/xml/stk_xml.h \
		mem/stk_mem.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		cipher/stk_base64.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_xml.o file/xml/stk_xml.cpp

stk_hash_crc32.o: hash/stk_hash_crc32.cpp text/stk_cstr_utils.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		threads/stk_threads.h \
		cpu/stk_cpu.h \
		hash/stk_hash_crc32.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_hash_crc32.o hash/stk_hash_crc32.cpp

stk_hash_md5.o: hash/stk_hash_md5.cpp mem/stk_mem.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		hash/stk_hash_md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_hash_md5.o hash/stk_hash_md5.cpp

stk_hash_password.o: hash/stk_hash_password.cpp text/stk_cstr_utils.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		hash/stk_hash_password.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_hash_password.o hash/stk_hash_password.cpp

stk_hash_ssc1.o: hash/stk_hash_ssc1.cpp text/stk_cstr_utils.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		io/stk_console.h \
		hash/stk_hash_ssc1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_hash_ssc1.o hash/stk_hash_ssc1.cpp

md5.o: hash/md5/md5.c hash/md5/md5.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md5.o hash/md5/md5.c

hmac_sha1.o: hash/sha1/hmac_sha1.c hash/sha1/hmac_sha1.h \
		hash/sha1/sha.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o hmac_sha1.o hash/sha1/hmac_sha1.c

sha1.o: hash/sha1/sha1.c hash/sha1/sha.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o sha1.o hash/sha1/sha1.c

stk_file_io.o: io/stk_file_io.cpp io/stk_file_io.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_file_io.o io/stk_file_io.cpp

stk_rs232.o: io/stk_rs232.cpp text/stk_cstr_utils.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		io/stk_console.h \
		io/stk_rs232.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_rs232.o io/stk_rs232.cpp

stk_console.o: io/stk_console.cpp text/stk_cstr_utils.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		threads/stk_threads.h \
		cpu/stk_cpu.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_console.o io/stk_console.cpp

stk_kop32_class.o: koperek/stk_kop32_class.cpp koperek/stk_kop32_class.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_stack.h \
		text/stk_cstr_class.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h \
		database/stk_database.h \
		database/stk_database_alias.h \
		database/stk_database_items.h \
		koperek/stk_kop32_options.h \
		hash/stk_hash_password.h \
		file/eno/stk_file_lzst_header.h \
		koperek/stk_kop32_list.h \
		koperek/stk_kop32_controler.h \
		koperek/stk_kop32_search.h \
		io/stk_file_io.h \
		compression/stk_compression_API.h \
		cipher/stk_cipher_API.h \
		hash/stk_hash_API.h \
		hash/stk_hash_md5.h \
		hash/stk_hash_ssc1.h \
		pharser/stk_pharse_command_line.h \
		threads/stk_threads.h \
		cpu/stk_cpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_kop32_class.o koperek/stk_kop32_class.cpp

stk_kop32_controler.o: koperek/stk_kop32_controler.cpp koperek/stk_kop32_controler.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		koperek/stk_kop32_class.h \
		text/stk_cstr_stack.h \
		text/stk_cstr_class.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h \
		database/stk_database.h \
		database/stk_database_alias.h \
		database/stk_database_items.h \
		koperek/stk_kop32_options.h \
		hash/stk_hash_password.h \
		file/eno/stk_file_lzst_header.h \
		koperek/stk_kop32_list.h \
		koperek/stk_kop32_search.h \
		io/stk_file_io.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_kop32_controler.o koperek/stk_kop32_controler.cpp

stk_kop32_search.o: koperek/stk_kop32_search.cpp koperek/stk_kop32_search.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		koperek/stk_kop32_controler.h \
		database/stk_database.h \
		database/stk_database_alias.h \
		text/stk_cstr_class.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h \
		database/stk_database_items.h \
		io/stk_file_io.h \
		koperek/stk_kop32_class.h \
		text/stk_cstr_stack.h \
		koperek/stk_kop32_options.h \
		hash/stk_hash_password.h \
		file/eno/stk_file_lzst_header.h \
		koperek/stk_kop32_list.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_kop32_search.o koperek/stk_kop32_search.cpp

stk_kop32_socket_server.o: koperek/stk_kop32_socket_server.cpp koperek/stk_kop32_socket_server.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		koperek/stk_kop32_API.h \
		koperek/stk_kop32_class.h \
		text/stk_cstr_stack.h \
		text/stk_cstr_class.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h \
		database/stk_database.h \
		database/stk_database_alias.h \
		database/stk_database_items.h \
		koperek/stk_kop32_options.h \
		hash/stk_hash_password.h \
		file/eno/stk_file_lzst_header.h \
		koperek/stk_kop32_list.h \
		koperek/stk_kop32_controler.h \
		koperek/stk_kop32_search.h \
		io/stk_file_io.h \
		sockets/stk_sockets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_kop32_socket_server.o koperek/stk_kop32_socket_server.cpp

stk_kop32_API.o: koperek/stk_kop32_API.cpp koperek/stk_kop32_API.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		koperek/stk_kop32_class.h \
		text/stk_cstr_stack.h \
		text/stk_cstr_class.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h \
		database/stk_database.h \
		database/stk_database_alias.h \
		database/stk_database_items.h \
		koperek/stk_kop32_options.h \
		hash/stk_hash_password.h \
		file/eno/stk_file_lzst_header.h \
		koperek/stk_kop32_list.h \
		koperek/stk_kop32_controler.h \
		koperek/stk_kop32_search.h \
		io/stk_file_io.h \
		process_journal/stk_journal.h \
		hash/stk_hash_ssc1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_kop32_API.o koperek/stk_kop32_API.cpp

stk_mem.o: mem/stk_mem.cpp cpu/stk_cpu.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		threads/stk_threads.h \
		io/stk_console.h \
		stk_vector.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_mem.o mem/stk_mem.cpp

stk_btree.o: mem/stk_btree.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_btree.o mem/stk_btree.cpp

stk_journal.o: process_journal/stk_journal.cpp process_journal/stk_journal.h \
		io/stk_console.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		threads/stk_threads.h \
		cpu/stk_cpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_journal.o process_journal/stk_journal.cpp

stk_pharse_command_line.o: pharser/stk_pharse_command_line.cpp pharser/stk_pharse_command_line.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_pharse_command_line.o pharser/stk_pharse_command_line.cpp

stk_pharse_math.o: pharser/stk_pharse_math.cpp pharser/stk_pharse_math.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_pharse_math.o pharser/stk_pharse_math.cpp

stk_sockets.o: sockets/stk_sockets.cpp sockets/stk_sockets.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		file/stk_file_mime_types.h \
		io/stk_console.h \
		threads/stk_threads.h \
		cpu/stk_cpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_sockets.o sockets/stk_sockets.cpp

stk_stasm.o: stasm/stk_stasm.cpp stasm/stk_stasm.h \
		stk_main.h \
		time/stk_time.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_stasm.o stasm/stk_stasm.cpp

stk_threads.o: threads/stk_threads.cpp threads/stk_threads.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		cpu/stk_cpu.h \
		mem/stk_mem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_threads.o threads/stk_threads.cpp

stk_cstr_utils.o: text/stk_cstr_utils.cpp text/stk_cstr_utils.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_cstr_utils.o text/stk_cstr_utils.cpp

stk_time.o: time/stk_time.cpp time/stk_time.h \
		stk_main.h \
		stasm/stk_stasm.h \
		mem/stk_mem.h \
		text/stk_cstr_utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_time.o time/stk_time.cpp

stk_cstr_class.o: text/stk_cstr_class.cpp text/stk_cstr_class.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_cstr_class.o text/stk_cstr_class.cpp

stk_cstr_stack.o: text/stk_cstr_stack.cpp text/stk_cstr_stack.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		text/stk_cstr_class.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_cstr_stack.o text/stk_cstr_stack.cpp

stk_kop32_options.o: koperek/stk_kop32_options.cpp koperek/stk_kop32_options.h \
		database/stk_database.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		database/stk_database_alias.h \
		text/stk_cstr_class.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h \
		database/stk_database_items.h \
		hash/stk_hash_password.h \
		file/eno/stk_file_lzst_header.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_kop32_options.o koperek/stk_kop32_options.cpp

stk_kop32_list.o: koperek/stk_kop32_list.cpp koperek/stk_kop32_list.h \
		database/stk_database.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h \
		database/stk_database_alias.h \
		text/stk_cstr_class.h \
		text/stk_cstr_utils.h \
		mem/stk_mem.h \
		stk_vector.h \
		io/stk_console.h \
		database/stk_database_items.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stk_kop32_list.o koperek/stk_kop32_list.cpp

miniz.o: file/zip/miniz.c file/zip/miniz.h \
		stk_main.h \
		time/stk_time.h \
		stasm/stk_stasm.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o miniz.o file/zip/miniz.c

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

